name:                AOC2024
version:             0.1.0.0
github:              "githubuser/AOC2024"
license:             BSD-3-Clause
author:              "Nick Straw"
maintainer:          "nick@broxholme.com"
copyright:           "2024 N J Straw"

default-extensions: GHC2021

extra-source-files:
- README.md

description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- containers
- hashable
- split
- timeit
- unordered-containers
- vector
- parsers
- array
- bimap
- comonad
- regex-applicative
- scientific
- MemoTrie
- recursion-schemes
- pqueue
- trie-simple

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  AOC2024-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N #M16000M

    dependencies:
    - AOC2024

tests:
  AOC2024-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2024
